language: objective-c

before_install:
  - git submodule update --init --recursive
  - brew update
  - brew upgrade xctool

xcode_project: RNCryptor.xcodeproj
xcode_scheme: RNCryptor
xcode_sdk: iphonesimulator9.0
